### ISSUE TITLE
6.1.x Versions missing

### ISSUE THREAD

**Issue by pietbrauer** [SAP-samples/cloud-sdk-ios-specs#17]
Hello,

I was just checking if there are newer Versions for Xcode 13 and found that even the versions 6.1.1, 6.1.2 and 6.1.3 (https://help.sap.com/viewer/fc1a59c210d848babfb3f758a6f55cb1/Latest/en-US/cc8678e3bc7343b797c2614574b0525a.html) are missing from the CocoaPods Spec repo.

Could you release them?

Thanks,

Piet

**Comment by MarcoEidinger** [comment]
@ramavana @serajahmad01 please take over as discussed via email. Thanks

**Comment by MarcoEidinger** [comment]
Hi @pietbrauer, thank you very much for your feedback! Do you use CocoaPods or is your inquiry primarily about Xcode 13 compatibility. For the latter we are still working on that as communicated [here](https://answers.sap.com/answers/13485735/view.html):

> Version 6.x of `SAPFiori` binary framework is not compatible with Xcode 13 beta and most likely will not be compatible with the final Xcode 13 version (to be released on September 20, ~ 10am PST).
> 
> The incompatibility is due to a compiler change by Apple, which changes the interface of UIKit. Previously in Xcode 12 an initializer marked as unavailable was still part of the swiftinterface and considered to be a mistake. This mistake was corrected in Xcode 13 by Apple but is an incompatible change. Therefore Xcode 13 will raise an error for SAPFiori's swiftinterface compiled with Xcode 12 and using UIKit.
> 
> Hence, SAP BTP SDK for iOS team is required to re-compile and re-publish SAPFiori with Xcode 13. Due to compliance reasons, SAP cannot do this based on Xcode beta software. Once Xcode 13 is officially released, SAP has to upgrade its central build system to use Xcode 13. Finally, the SAP BTP SDK for iOS team can work on re-compiling and re-publishing SAPFiori with Xcode 13. Once the new binary was published by SAP, you will find more information in SAP BTP SDK for iOS release notes.
> 
> In the meantime, as a manual workaround, you can remove the keyword override in SAPFiori.framework/Modules/SAPFiori.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:12065:33 to make SAPFiori work in Xcode 13. For Xcode 12, please use the original SAPFiori binary framework and its binary framework.
> 
> Please note:
> 
> All the other SAP BTP SDK for iOS binary frameworks in version 6.x are compatible with Xcode 13.
> Also, all SAP BTP SDK for iOS binary frameworks, including SAPFiori, in version 5.x are compatible with Xcode 13.

Letting us know if you are using CocoaPods would help us with our planning to regularly update Podspecs.

**Comment by pietbrauer** [comment]
Hey @MarcoEidinger,

it’s both. I am responsible for several internal apps in our company so using cocoapods helps keeping my sanity when updating the Frameworks and also aligns the installation process for alle 3rd party dependencies in the apps.

But of course I am also interested in using Xcode 13 quite soon hence I was looking for the latest frameworks.

Hope this helps.

**Comment by MarcoEidinger** [comment]
Hi @pietbrauer,

thanks for the info. We'll provide missing specs for 6.0.3 (iOS 14), 6.1.0 - 6.1.4 (iOS 13) in pull request #18. 
Unfortunately, none of those SAPFiori binaries are compatible with Xcode 13.

In the next couple of days we'll probably be able to publish a 6.1.x patch version that is compatible with Xcode 13.

**Comment by MarcoEidinger** [comment]
Hi @pietbrauer, versions up to 6.1.4 are available as podspecs.
