### ISSUE TITLE
Release Binaries 6.1.5, 6.1.7

### ISSUE THREAD

**Issue by pietbrauer** [SAP-samples/cloud-sdk-ios-specs#19]
Hate to be that guy again but I really want to drop iOS 14 and switch to Xcode 13.

Could you release the versions 6.1.5 and 6.1.7 for CocoaPods as well? https://help.sap.com/viewer/fc1a59c210d848babfb3f758a6f55cb1/Latest/en-US/cc8678e3bc7343b797c2614574b0525a.html

Thanks a lot!

**Comment by serajahmad01** [comment]
Hi @pietbrauer ,

We published the missing specs for 6.1.5 (Xcode 12.5) and 6.1.7 (Xcode 13) via the below PRs:
#20 for version 6.1.5 with support of XCode 12.5
#21 for version 6.1.7 with support of XCode 13.

Note: Patches in the future will be released to be either suitable for XCode12.5 or XCode13. So, choose the version as per your requirement.

Thanks
