### ISSUE TITLE
Version for Xcode 11.2

### ISSUE THREAD

**Issue by pietbrauer** [SAP-samples/cloud-sdk-ios-specs#5]
It seems that the version 4.0 SP00 PL04 for Xcode 11.2 was released.

Could you update the Specs Repo as well?

Thanks a ton,

Piet.

**Comment by sstadelman** [comment]
@pietbrauer done.  Will be adding for 4.0.6 and 4.0.7 when available in the repository as well.

**Comment by pietbrauer** [comment]
Thanks a lot!
