### ISSUE TITLE
Version for Xcode 11.4

### ISSUE THREAD

**Issue by pietbrauer** [SAP-samples/cloud-sdk-ios-specs#6]
Hello again,

could we have the latest version 5.0.4 available via CocoaPods?

Thanks a lot,

Piet

**Comment by sstadelman** [comment]
4.0.16 with Xcode 11.4 compatibility available.  5.0.4 in progress.

**Comment by pietbrauer** [comment]
All the 4.0.16 Cocoapods Versions point to a 4.0.15 version on the Nexus, is that correct?
Somehow I get a 403 when trying to download them.

**Comment by sstadelman** [comment]
The 4.0.15 binaries are pinned to version 4.0.16, since we needed to re-notarize the Assistant.  In general, these would usually not get out of sync.

I verified that they download successfully, maybe there was a connection or cURL issue.

Added 5.0.3 and 5.0.4 binaries also.

**Comment by pietbrauer** [comment]
I still can't download the new versions because I get a 403, whereas I can easily download Versions 4.0.6 and prior.
It seems that all older versions point to `maven73555000100900003122` but the new versions point to `maven73554900100900004651` which seems not to be available to outsiders.
Could you take another look at the permissions of the artficatory?

**Comment by sstadelman** [comment]
Permissions issue resolved in #7
