### ISSUE TITLE
Unable to download new versions

### ISSUE THREAD

**Issue by pietbrauer** [SAP-samples/cloud-sdk-ios-specs#7]
As there is no one responding on the old ticket…

I still can't download the new versions because I get a 403, whereas I can easily download Versions 4.0.6 and prior.
It seems that all older versions point to `maven73555000100900003122` but the new versions point to `maven73554900100900004651` which seems not to be available to outsiders.
Could you take another look at the permissions of the artficatory?

**Comment by sstadelman** [comment]
Being reviewed by the devops team. Can’t reproduce with my credentials.

**Comment by sstadelman** [comment]
@pietbrauer we believe the issue is resolved
