### ISSUE TITLE
Pod files not uploading to github repo

### ISSUE THREAD

**Issue by Udit-sys** [SAP-samples/cloud-sdk-ios-specs#8]
Hi I am using cloud framework with pods, but when i push my code to my Repo it gives me error:

remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: error: File src/xcode/Pods/SAPFiori/SAPFiori.framework/SAPFiori is 102.18 MB; this exceeds GitHub Enterprise's file size limit of 100.00 MB
To https://github.wdf.sap.corp/I500974/IEL_iOS.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://github.wdf.sap.corp/I500974/IEL_iOS.git'

Can you help me resolve it.

**Comment by sstadelman** [comment]
I would recommend adding Pods/ to your gitignore. Secondary machines may then download the dependencies themselves. 

Check out gitignore.io and search “cocoapods” for samples. 

Or, enabling large file storage on your GitHub acct is an option as well.

**Comment by Udit-sys** [comment]
Hey,

Thanks for your respone. 
Actually i am trying to build my project with SAP Xmake tool and it is not taking .gitignore.

Please advise.

**Comment by sstadelman** [comment]
Let's handle xmake issues internally, as that is not a public tool, and internallyyou ought to be consuming the binaries from a different nexus repository entirely.
